
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package esercitazione5;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int T_WHILE = 19;
  public static final int T_POW = 38;
  public static final int T_FLOAT = 8;
  public static final int T_ELSE = 18;
  public static final int T_READ = 22;
  public static final int T_EQ = 40;
  public static final int T_LBRAC = 27;
  public static final int T_THEN = 17;
  public static final int T_FALSE = 33;
  public static final int T_LPAR = 25;
  public static final int T_INT = 7;
  public static final int T_TO = 20;
  public static final int T_OUT = 14;
  public static final int T_FOR = 15;
  public static final int T_ASSIGN = 30;
  public static final int T_NE = 41;
  public static final int T_RETURN = 31;
  public static final int T_NOT = 48;
  public static final int T_AND = 46;
  public static final int T_DIV = 37;
  public static final int T_GT = 44;
  public static final int T_CHAR = 11;
  public static final int EOF = 0;
  public static final int T_RBRAC = 28;
  public static final int T_MINUS = 35;
  public static final int T_WRITE = 23;
  public static final int T_STR_CONCAT = 39;
  public static final int error = 1;
  public static final int T_SEMI = 3;
  public static final int T_REAL_CONST = 50;
  public static final int T_GE = 45;
  public static final int T_COMMA = 4;
  public static final int T_WRITELN = 24;
  public static final int T_STRING = 9;
  public static final int T_RPAR = 26;
  public static final int T_BOOL = 10;
  public static final int T_CHAR_CONST = 52;
  public static final int T_STRING_CONST = 51;
  public static final int T_LOOP = 21;
  public static final int T_PLUS = 34;
  public static final int T_LT = 42;
  public static final int T_MAIN = 2;
  public static final int T_OR = 47;
  public static final int T_INTEGER_CONST = 49;
  public static final int T_DEF = 13;
  public static final int T_TRUE = 32;
  public static final int T_PIPE = 5;
  public static final int T_TIMES = 36;
  public static final int T_IF = 16;
  public static final int T_ID = 53;
  public static final int T_COLON = 29;
  public static final int T_LE = 43;
  public static final int T_VAR = 6;
  public static final int T_VOID = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "T_MAIN",
  "T_SEMI",
  "T_COMMA",
  "T_PIPE",
  "T_VAR",
  "T_INT",
  "T_FLOAT",
  "T_STRING",
  "T_BOOL",
  "T_CHAR",
  "T_VOID",
  "T_DEF",
  "T_OUT",
  "T_FOR",
  "T_IF",
  "T_THEN",
  "T_ELSE",
  "T_WHILE",
  "T_TO",
  "T_LOOP",
  "T_READ",
  "T_WRITE",
  "T_WRITELN",
  "T_LPAR",
  "T_RPAR",
  "T_LBRAC",
  "T_RBRAC",
  "T_COLON",
  "T_ASSIGN",
  "T_RETURN",
  "T_TRUE",
  "T_FALSE",
  "T_PLUS",
  "T_MINUS",
  "T_TIMES",
  "T_DIV",
  "T_POW",
  "T_STR_CONCAT",
  "T_EQ",
  "T_NE",
  "T_LT",
  "T_LE",
  "T_GT",
  "T_GE",
  "T_AND",
  "T_OR",
  "T_NOT",
  "T_INTEGER_CONST",
  "T_REAL_CONST",
  "T_STRING_CONST",
  "T_CHAR_CONST",
  "T_ID"
  };
}

